# Explore Cofffee

Create your own EDA below! Create as many code-blocks as you need.

Once you've completed your EDA, complete the section titled **Reflections** where you will answer questions about your EDA.

In [1]:
import pandas as pd 
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# import data
coffee = pd.read_csv("../data/crop/coffee_output.csv")

In [5]:
# TODO: view first 5 rows of your data
coffee.head()

,country,subdivision,type,60kgs_bag,year,nonbearing_trees,bearing_trees,nonbear_hectares,bearing_hectares,bearing_trees_per_hectare,nonbearing_trees_per_hectare
0,Brazil,Minas Gerais,Arabica,16.2,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
1,Brazil,Espirito Santo,Arabica,2.2,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
2,Brazil,Espirito Santo,Robusta,7.5,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
3,Brazil,Sao Paulo,Arabica,3.2,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
4,Brazil,Parana,Arabica,0.5,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0

In [4]:
# TODO: describe your numeric columns
coffee.describe()

,60kgs_bag,year,nonbearing_trees,bearing_trees,nonbear_hectares,bearing_hectares,bearing_trees_per_hectare,nonbearing_trees_per_hectare
count,114.000000,114.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000
mean,8.812281,2012.552632,994.495413,5646.926606,298.055046,2146.513761,2639.027523,3345.082569
std,9.051550,6.265642,310.338484,372.684151,97.572559,96.699000,245.497999,175.124513
min,0.500000,2002.000000,466.000000,4465.000000,148.000000,2010.000000,2106.000000,3030.000000
25%,2.600000,2007.000000,679.000000,5640.000000,205.000000,2070.000000,2552.000000,3191.000000
50%,4.750000,2013.000000,1050.000000,5735.000000,307.000000,2135.000000,2679.000000,3415.000000
75%,12.175000,2018.000000,1185.000000,5810.000000,347.000000,2223.000000,2786.000000,3483.000000
max,34.800000,2023.000000,1510.000000,6200.000000,495.000000,2360.000000,3020.000000,3578.000000

In [6]:
# TODO: display the null values in your dataframe
coffee.isnull()

,country,subdivision,type,60kgs_bag,year,nonbearing_trees,bearing_trees,nonbear_hectares,bearing_hectares,bearing_trees_per_hectare,nonbearing_trees_per_hectare
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
109,False,False,False,False,False,False,False,False,False,False,False
110,False,False,False,False,False,False,False,False,False,False,False
111,False,False,False,False,False,False,False,False,False,False,False
112,False,False,False,False,False,False,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False,False

In [10]:
# TODO: drop your null values
coffee.dropna()

,country,subdivision,type,60kgs_bag,year,nonbearing_trees,bearing_trees,nonbear_hectares,bearing_hectares,bearing_trees_per_hectare,nonbearing_trees_per_hectare
0,Brazil,Minas Gerais,Arabica,16.2,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
1,Brazil,Espirito Santo,Arabica,2.2,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
2,Brazil,Espirito Santo,Robusta,7.5,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
3,Brazil,Sao Paulo,Arabica,3.2,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
4,Brazil,Parana,Arabica,0.5,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
...,...,...,...,...,...,...,...,...,...,...,...
109,Brazil,Minas Gerais,Arabica,28.5,2023,1510.0,6100.0,475.0,2020.0,3020.0,3179.0
110,Brazil,Espirito Santo,Arabica,4.4,2023,1510.0,6100.0,475.0,2020.0,3020.0,3179.0
111,Brazil,Espirito Santo,Robusta,16.6,2023,1510.0,6100.0,475.0,2020.0,3020.0,3179.0
112,Brazil,Sao Paulo,Arabica,5.1,2023,1510.0,6100.0,475.0,2020.0,3020.0,3179.0
113,Brazil,Parana,Arabica,0.8,2023,1510.0,6100.0,475.0,2020.0,3020.0,3179.0

In [17]:
# TODO: Select only Minas Gerais
coffee_mg = coffee[coffee["subdivision"] == "Minas Gerais"]
coffee_mg

,country,subdivision,type,60kgs_bag,year,nonbearing_trees,bearing_trees,nonbear_hectares,bearing_hectares,bearing_trees_per_hectare,nonbearing_trees_per_hectare
0,Brazil,Minas Gerais,Arabica,16.20,2002,1500.0,4465.0,495.0,2120.0,2106.0,3030.0
5,Brazil,Minas Gerais,Arabica,26.70,2003,1125.0,5265.0,315.0,2360.0,2231.0,3577.0
10,Brazil,Minas Gerais,Arabica,14.40,2004,631.0,5050.0,205.0,2174.0,2323.0,3075.0
15,Brazil,Minas Gerais,Arabica,21.40,2005,466.0,5255.0,148.0,2305.0,2280.0,3149.0
20,Brazil,Minas Gerais,Arabica,16.30,2006,581.0,5330.0,175.0,2298.0,2319.0,3320.0
25,Brazil,Minas Gerais,Arabica,23.70,2007,563.0,5730.0,186.0,2245.0,2552.0,3030.0
30,Brazil,Minas Gerais,Arabica,16.85,2008,679.0,5720.0,196.0,2235.0,2559.0,3468.0
35,Brazil,Minas Gerais,Arabica,25.55,2009,663.0,5770.0,188.0,2223.0,2596.0,3527.0
40,Brazil,Minas Gerais,Arabica,22.10,2010,873.0,5725.0,244.0,2151.0,2662.0,3578.0
45,Brazil,Minas Gerais,Arabica,28.50,2011,815.0,5820.0,234.0,2175.0,2676.0,3483.0
50,Brazil,Minas Gerais,Arabica,23.50,2012,835.0,5760.0,260.0,2150.0,2679.0,3212.0
55,Brazil,Minas Gerais,Arabica,28.50,2013,1000.0,5860.0,282.0,2105.0,2784.0,3546.0
60,Brazil,Minas Gerais,Arabica,29.40,2014,1055.0,5810.0,307.0,2135.0,2721.0,3436.0
69,Brazil,Minas Gerais,Arabica,26.00,2015,1185.0,5770.0,347.0,2090.0,2761.0,3415.0
74,Brazil,Minas Gerais,Arabica,25.30,2016,1125.0,5735.0,340.0,2070.0,2771.0,3309.0
79,Brazil,Minas Gerais,Arabica,32.50,2017,1300.0,5640.0,380.0,2020.0,2792.0,3421.0
84,Brazil,Minas Gerais,Arabica,28.30,2018,NaN,NaN,NaN,NaN,NaN,NaN
89,Brazil,Minas Gerais,Arabica,34.20,2019,1150.0,5740.0,335.0,2060.0,2786.0,3433.0
94,Brazil,Minas Gerais,Arabica,29.10,2020,1230.0,5700.0,350.0,2040.0,2794.0,3514.0
99,Brazil,Minas Gerais,Arabica,34.80,2021,1050.0,6200.0,320.0,2100.0,2952.0,3281.0
104,Brazil,Minas Gerais,Arabica,24.50,2022,1500.0,6010.0,470.0,2010.0,2990.0,3191.0
109,Brazil,Minas Gerais,Arabica,28.50,2023,1510.0,6100.0,475.0,2020.0,3020.0,3179.0

In [ ]:
# TODO: BEGIN YOUR EDA!

## Reflections

Answer each question based on the visualizations that you've generated.

Remember, you must justify your answers with proof! Look back to W6D3 for more context.

How is bearing trees changing across the years for Minas Gerais? Is this increasing or decreasing? What is the distribution of this variable? Is it normal?

Answer here

How is bearing hectares changing across the years for Minas Gerais? Is this increasing or decreasing? What is the distribution of this variable? Is it normal?

Answer here

How is the count of million 60kgs bags of coffee changing across the years for Minas Gerais? Is this increasing or decreasing? What is the distribution of this variable? Is it normal?

Answer here

What is the relationship between bearing_trees and 60kgs_bag? How *strong* is this relationship? Use pearson's correlation coefficient.

Answer here

What is the relationship between bearing_hectares and 60kgs_bag? How *strong* is this relationship? Use pearson's correlation coefficient.

Answer here